apiVersion: v1
kind: Config
clusters:
- name: democluster
  cluster:
    server: https://democluster-ocid1.cluster.oc1.ap-mumbai-1.aaaaaaaadw663g43jq22goboifswlgrzaf5hhgr642knxrnvycvoz37uf3kq.cluster.ap-mumbai-1.155.248.246.170:6443
    certificate-authority: demoprojects/k8s/ca.crt
users:
- name: gitactions-user
  user:
    client-certificate: demoprojects/k8s/gitactions-user-cert.pem
    client-key: demoprojects/k8s/gitactions-user-key.pem
contexts:
- name: gitactions-context
  context:
    cluster: democluster
    user: gitactions-user
current-context: gitactions-context
