name: Build Docker Container and Deploy to Oracle Kubernetes

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker container
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: novajack/webapk:latest

      - name: Configure kubectl for Oracle Kubernetes Engine
        run: |
          mkdir -p $HOME/.kube
          cp kubeconfig.yaml $HOME/.kube/config

      - name: Run kubectl apply
        run: kubectl apply -f demoprojects/kubernetes/deployment.yaml
