name: Build Docker Container and Deploy to Oracle Kubernetes

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker container
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: novajack/webapk:latest

      - name: Install Oracle Cloud CLI
          run: |
          curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh | bash -s -- --accept-all-defaults	

      - name: Configure Oracle Cloud CLI
        run: |
          oci setup config --region ap-mumbai-1 --tenancy ocid1.tenancy.oc1..aaaaaaaauoff3cbgepdtsiwg6o6hqqfuwb7t6zwd3sbuberqgrs2owxsmxgq --user ocid1.user.oc1..aaaaaaaa333nsyqyvgradxe33gyjpglqpu5dcrwmlt34kn4x3pgmscw43haq

      - name: Install kubectl
        run: |
          sudo apt-get update -q
          sudo apt-get install -q -y kubectl

      - name: Configure kubectl for Oracle Kubernetes Engine
        run: |
          mkdir -p $HOME/.kube
          cp kubeconfig.yaml $HOME/.kube/config
          echo "$KUBECONFIG" >> $HOME/.bashrc
          source $HOME/.bashrc

      - name: Run kubectl apply
        run: kubectl apply -f kubernetes/deployment.yaml

