name: Build Docker Container and Deploy to OKE

on:
  push:
    branches:
      - main
      - master

env:
  OCI_CLI_REGION: ap-mumbai-1

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker container
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: novajack/webapk:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Update OCI CLI
        run: pip install --upgrade oci-cli

      - name: Configure Kubectl
        uses: oracle-actions/configure-kubectl-oke@v1.0
        with:
          cluster: ${{ secrets.OKE_CLUSTER_OCID }}
        env:
          OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
          OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
          OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
          OCI_CLI_PRIVATE_KEY: ${{ secrets.OCI_CLI_PRIVATE_KEY }}
          OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}

      - name: Run Python Script
        run: python main.py
