name: Install OCI CLI

on:
  push:
    branches:
      - main

jobs:
  install-oci-cli:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install OCI CLI
      run: |
        for i in {1..3}; do
          curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh | bash && break || sleep 15;
        done

    - name: Verify OCI CLI Installation
      run: oci --version
