name: Build Docker Container and Deploy to OKE

on:
  push:
    branches:
      - main
      - master

env:
  OCI_CLI_REGION: ap-mumbai-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker container
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: novajack/webapk:latest

      - name: Install OCI CLI
        run: |
          for i in {1..3}; do
            curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh | bash && break || sleep 15;
          done
        shell: bash

      - name: Configure OCI CLI
        run: |
          echo "[DEFAULT]" > $HOME/.oci/config
          echo "user=${{ secrets.OCI_CLI_USER }}" >> $HOME/.oci/config
          echo "tenancy=${{ secrets.OCI_CLI_TENANCY }}" >> $HOME/.oci/config
          echo "fingerprint=${{ secrets.OCI_CLI_FINGERPRINT }}" >> $HOME/.oci/config
          echo "key_file=${{ secrets.OCI_CLI_PRIVATE_KEY }}" >> $HOME/.oci/config
          echo "region=${{ env.OCI_CLI_REGION }}" >> $HOME/.oci/config

      - name: Create kubeconfig directory
        run: mkdir -p $HOME/.kube

      - name: Login to Docker Hub (again, if needed)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker container (again, if needed)
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: novajack/webapk:latest
