name: Build Docker Container and Deploy to Kubernetes

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker container
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: novajack/webapk:latest

      - name: Set up Kubernetes context
        uses: azure/setup-kubectl@v1
        with:
          kubeconfig: k8s/kubeconfig.yaml
          
      - name: Checkout Repository
      uses: actions/checkout@v2

      - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Kubernetes CLI
      uses: azure/kubernetes-cli@v1
      with:
        installKubectl: true

    - name: Run kubectl apply
      run: kubectl apply -f demoprojects/kubernetes/deployment.yaml
