name: Build and Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: novajack/webapk:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - name: Install doctl
        run: |
          curl -sL https://github.com/digitalocean/doctl/releases/download/v1.62.0/doctl-1.62.0-linux-amd64.tar.gz | tar -xzv
          sudo mv doctl /usr/local/bin
      - name: Authenticate with Digital Ocean
        run: doctl auth init -t ${{ secrets.DIGITALOCEAN_API_TOKEN }}
      - name: Configure kubectl
        run: |
          mkdir -p ~/.kube
          doctl kubernetes cluster kubeconfig save kubecluster

      # Apply Deployment and Service manifests
      - name: Apply Deployment and Service
        run: |
          curl -sLO https://raw.githubusercontent.com/nova-jack/demoprojects/main/kubernetes/deployment.yaml
          kubectl apply -f deployment.yaml

          curl -sLO https://raw.githubusercontent.com/nova-jack/demoprojects/main/kubernetes/service.yaml
          kubectl apply -f service.yaml

      # Trigger a rollout (assuming your Deployment is named "your-app")
      - name: Update Deployment in Digital Ocean Kubernetes
        run: |
          kubectl rollout restart deployment your-app
