name: Install OCI CLI

on:
  push:
    branches:
      - main

jobs:
  install-oci-cli:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: your-python-version

    - name: Install OCI CLI
      run: |
        curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh | bash -s -- --accept-all-defaults --oci-cli-version=your-oci-cli-version
        mv ~/.oci/cli /root/bin
        echo 'export PATH=$PATH:/root/bin' >> $GITHUB_ENV

    - name: Verify OCI CLI Installation
      run: oci --version
