name: Build Docker Container and Deploy to Kubernetes

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Consider removing this step if not using Buildx features
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker container
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: novajack/webapk:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f demoprojects/kubernetes/deployment.yaml
          kubectl apply -f demoprojects/kubernetes/service.yaml

      - name: Install OCI CLI
        run: |
          for i in {1..3}; do
          curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh | bash && break || sleep 15;
          done
        shell: bash


    env:
      # Ensure secrets are correctly set up
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_PRIVATE_KEY }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
      OKE_CLUSTER_OCID: ${{ secrets.OKE_CLUSTER_OCID }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure Kubectl
        uses: oracle-actions/configure-kubectl-oke@v1.3.2
        with:
          cluster: ${{ secrets.OKE_CLUSTER_OCID }}

      - name: Run Kubectl
        run: kubectl get nodes -A
