name: Build Docker Container and Deploy to OKE

on:
  push:
    branches:
      - main
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: novajack/webapk:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Configure Kubectl
        uses: oracle-actions/configure-kubectl-oke@v1.0
        with:
          cluster: ${{ secrets.OKE_CLUSTER_OCID }}
