name: Continuous Integration and Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python -m unittest discover -s tests

  build-docker:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v2

      - name: Build Docker Image
        run: |
          docker build -t your-image-name:latest .
          docker tag your-image-name:latest your-image-name:$(git rev-parse --short ${{ github.sha }})

      - name: Push Docker Image
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push your-image-name:latest
          docker push your-image-name:$(git rev-parse --short ${{ github.sha }})

  deploy-oke:
    runs-on: ubuntu-latest

    needs: build-docker

    env:
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_PRIVATE_KEY: ${{ secrets.OCI_CLI_PRIVATE_KEY }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
      OKE_CLUSTER_OCID: ${{ secrets.OKE_CLUSTER_OCID }}
    
    steps:
      - name: Install OCI CLI
        run: |
          for i in {1..3}; do
            curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh | bash && break || sleep 15;
          done
        shell: bash

      - name: Configure Kubectl for OKE
        uses: oracle-actions/configure-kubectl-oke@v1.3.2
        with:
          cluster: ${{ secrets.OKE_CLUSTER_OCID }}

      - name: Deploy to Oracle Kubernetes
        run: |
          echo "apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: your-app
          spec:
            replicas: 3
            selector:
              matchLabels:
                app: your-app
            template:
              metadata:
                labels:
                  app: your-app
              spec:
                containers:
                - name: your-app
                  image: your-image-name:$(git rev-parse --short ${{ github.sha }})
                  ports:
                  - containerPort: 5000" > deployment.yaml

          export KUBECONFIG=$HOME/.kube/config
          echo "${{ env.OCI_CLI_PRIVATE_KEY }}" > oci_api_key.pem
          oci ce cluster create-kubeconfig --cluster-id ${{ env.OKE_CLUSTER_OCID }} --file $KUBECONFIG --region ${{ env.OCI_CLI_REGION }} --token ${{ secrets.OCI_CLI_KEY_CONTENT }}
          
          kubectl apply -f deployment.yaml
